### ISSUE TITLE
ONB Logo

### ISSUE THREAD

**Issue by onbcst** [e-laute/e-laute.github.io#3]
ONB will have a modified logo from Janurary 2023 on. We'll need to update the logo on the landing page.

This issue is just a reminder to replace the logo mid January :)

**Comment by onbcst** [comment]
@musicog can you set a due-to date on this one? Thanks!

**Comment by musicog** [comment]
GitHub issues sadly don't support due dates at the moment - I would need to create a milestone, but that seems like over-reaching. Instead I'll set myself a reminder and contact you when the time comes!

**Comment by onbcst** [comment]
OK, understood. I'll do the same ;)

**Comment by onbcst** [comment]
Done.
